100-hours-a-week/7-team-ddb-fe

.prettierrc, .vscode/settings.json, components.json, package.json, pnpm-lock.yaml, src/app/globals.css, src/shared/components/alert-dialog/AlertDialog.tsx, src/shared/components/alert-dialog/Button.tsx, src/shared/components/alert-dialog/index.ts, src/shared/components/bottom-navigation/BottomNavigation.tsx, src/shared/components/bottom-navigation/BottomNavigationItem.tsx, src/shared/components/bottom-navigation/CenterButton.tsx, src/shared/components/bottom-navigation/index.ts, src/shared/components/bottom-navigation/navigation-config.tsx, src/shared/components/header/Header.tsx, src/shared/components/header/index.ts, src/shared/components/index.ts, src/shared/components/toaster/Toaster.tsx, src/shared/components/toaster/index.ts, src/shared/components/toaster/toaster.css, src/shared/index.ts, src/shared/lib/utils.ts
- 돌핀 서비스에서 사용 될 공통 컴포넌트 구현함
- 알람 다이얼로그
- 헤더
- 토스트
- 바텀 내비게이션 구현
Closes #24
=> Feat/#24 공통 컴포넌트 구현

package.json, pnpm-lock.yaml, src/features/place/components/index.ts, src/features/place/components/map/Map.tsx, src/features/place/components/map/index.ts, src/features/place/utils/index.ts, src/features/place/utils/map.ts, src/shared/lib/index.ts, src/shared/lib/map.ts, tsconfig.json
- 카카오맵 SDK 도입 
- 카카오맵 타입 추가
- 카카오맵 sdk 불러오는 함수 추가
- 카카오맵 utils 함수 추가
- map 컴포넌트 추가
Closes #1
=> Feat/#1 카카오맵 SDK 도입 

src/app/(main)/moments/page.tsx
임시 다이어리 페이지 구성
- 헤더 추가
- 곧 여러분을 찾아갈 새로운 기능을 준비 중이에요! 문구 추가
Closes #29
=> Feat/#29 다이어리 페이지 구성

src/app/(main)/(places)/search/page.tsx, src/features/place/api/getCategories.ts, src/features/place/api/getPlaceDetail.ts, src/features/place/api/index.ts, src/features/place/api/searchPlaces.ts, src/features/place/components/category-list/Category.tsx, src/features/place/components/category-list/CategoryList.tsx, src/features/place/components/map/Map.tsx, src/features/place/components/place-item/PlaceItem.tsx, src/features/place/components/place-list/PlaceList.tsx, src/features/place/components/search-result-bar/SearchResultBar.tsx, src/features/place/index.ts, src/features/place/types/place.ts, src/features/place/utils/map.ts
장소 검색, 카테고리 필터링, 지도 표시 기능 등 서비스의 핵심인 장소 관련 기능들을 구현하고 개선하는 데 중점을 두었습니다. 
-   **장소 검색 및 정보 기능 강화**
-   장소 검색 API 구현 (`018a988`)
-   장소 세부 정보 조회 API 구현 (`3c5835d`)
-   임시 검색 페이지 구성 (`d2ba7ec`)
-   `searchResultBar`가 쿼리 및 카테고리로 초기화되도록 설정 (`1daec87`)
-   `placeList` 클릭 기능 추가 (`c11bea1`)
-   **카테고리 기능 구현 및 개선**
-   카테고리 목록 조회 API 연동 및 관련 컴포넌트 분리 (`24bbd5d`)
-   카테고리 조회 API 구현 (`7265746`)
-   카테고리 응답 타입 정의 (`ac06812`)
-   **지도 기능 개선**
-   지도 초기 표시 위치 고정 값 지정 (`chore: 지도 초기 고정 값 지정`)
-   지도가 현재 위치 대신 고정된 위치를 중심으로 표시되도록 수정 (`8f79281`)
-   **기타**
-   컴포넌트 `index`를 통한 내보내기 구현 (`f07a706`)
Closes #36 
-   현재 검색 페이지는 임시로 구성되어 있으며, 추후 UI/UX 개선이 필요할 수 있습니다.
- API 연동 및 테스트가 필요합니다.
=> Feat/#36 임시 장소 API 연동

src/app/api/health/route.js
서버나 서비스가 정상적으로 작동 중인지 확인하기 위한 간단한 API 요청 구성했습니다. 
`/api/health` 해당 엔드포인트에서 200이 오는지 확인하면 됩니다.
- health check 라우터 구성
Closes #35
=> Feat#35 health check 라우터 구성

src/features/place/components/search-result-bar/SearchResultBar.tsx
/search 페이지 - 한 번 더 검색 후, 위치 정보 찾을 수 없는 오류
- url 수정
Closes #51 
https://github.com/100-hours-a-week/7-team-ddb-wiki/issues/59
=> Fix/#51 /search 페이지 - 한 번 더 검색 후, 위치 정보 찾을 수 없는 오류

next.config.ts, src/app/(auth)/oauth/kakao/callback/KakaoCallbackClient.tsx, src/features/place/components/map/Map.tsx, src/middleware.ts
로그인 미들웨어 추가
-로그인 미들웨어 추가
Closes #53 
회원가입, 동의 페이지에서 좀 더 디테일한 예외처리가 필요합니다.
=> Feat/#53 로그인 미들웨어 추가

src/features/place/api/getCategories.ts
- 추후 개선 예정
카테고리 prod 환경에서는 보이지 않는 오류
- ssr 렌더링으로 변경
Closes #54
=> Fix/#54 카테고리 prod 환경에서는 보이지 않는 오류, ssr 렌더링으로 변경

next.config.ts, src/app/(auth)/oauth/kakao/callback/KakaoCallbackClient.tsx, src/app/(main)/(places)/search/layout.tsx, src/app/(main)/(places)/search/page.tsx, src/app/(main)/mypage/page.tsx, src/app/globals.css, src/app/layout.tsx, src/features/place/api/getCategories.ts, src/features/place/components/map/Map.tsx, src/features/place/components/place-basic-info/PlaceBasicInfo.tsx, src/features/place/components/place-item/PlaceItem.tsx, src/features/place/components/place-list/PlaceList.tsx, src/middleware.ts
- 배포 이후 부족한 예외처리, 미들웨어, 로딩 화면을 개선하였습니다. 
- 로딩 화면 및 예외처리 
- 로그인 미들웨어 추가
- 카테고리 SSR 렌더링으로 변경
=> Release: merged main with improved loading & error UX

src/app/(auth)/auth/consent/page.tsx, src/app/(auth)/oauth/kakao/callback/KakaoCallbackClient.tsx, src/app/(main)/(places)/places/[id]/page.tsx, src/app/(main)/(places)/search/page.tsx, src/app/layout.tsx, src/features/place/components/place-basic-info/PlaceBasicInfo.tsx, src/features/place/components/place-menu/PlaceMenu.tsx, src/features/place/types/place.ts, src/features/user/api/issueAuthTokens.ts, src/features/user/api/postAgreement.ts, src/features/user/types/token.ts, src/middleware.ts, src/shared/providers/QueryProvider.tsx, src/shared/providers/index.ts
이번 PR은 `dev` 브랜치에서 개발된 주요 기능 및 버그 수정 사항을 `main` 브랜치에 반영합니다.  
상세 페이지 메뉴 예외처리, 변수명 개선, 타입 에러 수정, 뒤로가기 시 search 재검색 개선 등 다양한 개선 사항이 포함되어 있습니다.
- 상세 페이지에서 메뉴는 있으나 가격이 없는 경우 예외처리 (`Fix/#62`, #70)
- 백엔드와 변수명 일치 및 코드 리팩토링 (`Refactor/#39`, #69)
- lint 타입 에러 수정 (`chore`)
- 장소 상세보기 → 뒤로가기 시 search 재검색 개선 (`Refactor/#61`, #71)
- 로그 확인용 코드 추가 (`chore`)
- 메뉴 가격이 없는 경우 UI 및 데이터 처리 예외처리 추가
- 변수명 통일 및 가독성 향상
- 타입 에러 및 린트 이슈 해결
- tanstack query의 staleTime, refetch 옵션을 활용한 search 페이지 UX 개선
- 디버깅 및 로그 확인 코드 반영
- #62
- #39
- #61
- #70
- #69
- #71
- 병합 후 추가 테스트 권장
- 캐시 및 쿼리 관련 옵션 변경에 따른 예상치 못한 동작 여부 확인 필요
=> Release: merge dev with menu exception, variable refactor, and improved search UX

Dockerfile, Jenkinsfile, src/app/(auth)/auth/consent/page.tsx, src/app/(auth)/oauth/kakao/callback/page.tsx, src/features/user/components/consent/ConsentCard.tsx, src/features/user/components/consent/LocationConsent.tsx, src/features/user/components/consent/PrivacyConsent.tsx, src/features/user/components/consent/index.ts, src/features/user/components/index.ts, src/features/user/hooks/index.ts, src/features/user/hooks/useConsent.ts
정보 동의 페이지 리팩토링 및 상태 관리 방식 개선, 배포 관련 설정 파일 추가(Jenkinsfile, Dockerfile), 불필요한 주석 제거 등 dev 브랜치의 변경 사항을 main에 반영합니다.
- 정보 동의 페이지 컴포넌트 리팩토링
- 상태 관리를 위한 custom hook 추가 (`Refactor/#67`)
- Jenkinsfile, Dockerfile 작성 및 배포 설정 (`deploy: #99`)
- 불필요한 주석 제거 (`chore`)
- Closes #67
- Closes #99
=> Release: merge dev with consent page refactor and deploy config

Jenkinsfile
Jenkins에서 파이프라인이 시작되고 끝날 때 Discord 운영 채널에 알림을 보냅니다.
- 파이프라인 시작 시 디스코드 알림
- 파이프라인 마쳤을 시 결과 디스코드 알림
=> deploy: Jenkis Discord Webhook 추가

Jenkinsfile
prod : 월-금 오전 9:30
dev : 월-목 오후 12:30, 금: 오전 9:30, 토-일: 12:30
젠킨스가 자동으로 실행되도록 설정하였습니다. 
- cron 작업 추가
- dev, main branch 아닐 시 실행 중단
=> Deploy: cron 작업 추가

Jenkinsfile
배포 전 인프라 가용성 확인 로직을 도입하여, 안정적인 배포가 가능하게 하였습니다. 기존 cron 시간을 변경하여 안정성을 높였습니다. 
- SSH 기반 인프라 접근 확인을 수행하는 Check Infrastructure Availability 스테이지 추가
- SSH 연결 실패 시 Discord 알림 발송 후 파이프라인 종료
=> Deploy: 인프라 확인 후 실행

src/app/(main)/(places)/places/[id]/page.tsx, src/app/(main)/layout.tsx, src/app/(main)/moments/page.tsx, src/features/community/components/author-info/AuthorInfo.tsx, src/features/community/components/author-info/index.ts, src/features/community/components/index.ts, src/features/community/components/moment-list/MomentItem.tsx, src/features/community/components/moment-list/MomentList.tsx, src/features/community/components/moment-list/index.ts, src/features/community/index.ts, src/features/community/types/index.ts, src/features/community/types/moment.ts, src/features/community/utils/formatDate.ts, src/features/community/utils/index.ts, src/shared/components/bottom-navigation/BottomNavigation.tsx, src/shared/components/header/Header.tsx, src/shared/components/user-avatar/UserAvatar.tsx
커뮤니티 기능의 핵심인 기록 리스트 페이지를 구현하고, 관련 컴포넌트 및 유틸리티 함수를 추가하였습니다. 또한, 사용자 경험 향상을 위한 UI 수정도 함께 진행되었습니다.
- **기록 리스트 기능 구현:**
- `MomentList` 컴포넌트 신규 구현 및 기록 리스트 페이지에 적용
- 기록 작성자 정보를 표시하는 `AuthorInfo` 컴포넌트 구현
- 기록 리스트에 필요한 데이터 타입 정의 및 Mock 데이터 구성
- 시간 표시를 위한 포맷 함수 구현
- **UI 및 사용성 개선:**
- 헤더와 네비게이션 바가 스크롤 시 고정되지 않고 함께 움직이는 현상 수정
- `UserAvatar` 컴포넌트의 props 변경 (optional → null 허용)
- **기타:**
- 커뮤니티 관련 폴더 export 설정
- **`MomentList.tsx`**: 여러 개의 기록(모먼트)을 리스트 형태로 보여주는 컴포넌트입니다. 각 아이템은 `AuthorInfo`와 기록 내용을 포함합니다.
- **`AuthorInfo.tsx`**: 기록 작성자의 프로필 이미지(UserAvatar)와 닉네임, 작성 시간 등을 표시하는 컴포넌트입니다.
- **타입 및 Mock 데이터**: `Moment` (가칭) 등 기록 리스트에 필요한 타입을 정의하고, 개발/테스트를 위한 Mock 데이터를 구성하였습니다.
- **시간 포맷 함수**: 백엔드에서 전달받은 시간 데이터를 사용자 친화적인 형태로 변환하는 유틸리티 함수입니다.
- **스크롤 수정**: 헤더 및 네비바의 `position` 또는 관련 스타일을 조정하여 스크롤 시 의도치 않은 …
=> Feat/#131 기록 목록 페이지 UI 구성

src/features/community/hooks/index.ts, src/features/community/hooks/useInfiniteScroll.ts, src/shared/components/index.ts, src/shared/components/loading-spinner/LoadingSpinner.tsx, src/shared/components/loading-spinner/index.ts, src/shared/types/Infinite.ts, src/shared/types/index.ts
장소 목록 페이지에 무한 스크롤 기능을 구현하고, 로딩을 처리하는 UI를 추가했습니다.
- 무한 스크롤 기능 구현
- `useInfiniteScroll` 커스텀 훅 구현
- 무한 스크롤 데이터 타입 정의
- 스크롤 이벤트 처리 및 데이터 페이징 로직 추가
- UI 컴포넌트 추가
- `LoadingSpinner` 컴포넌트 구현
- 무한 스크롤 데이터 타입 선언
- 페이지네이션 데이터 구조 설계
Closes #145 
- 무한 스크롤 구현 시 메모리 누수 방지를 위해 이벤트 리스너 정리 필요
- 로딩 상태와 에러 상태가 적절히 처리되어야 함
- 스크롤 성능 최적화를 위해 디바운싱 적용
=> Feat/#145 무한스크롤 커스텀 훅 추가

src/app/(main)/error.tsx, src/shared/lib/fetchApi.ts
사용자 경험 개선을 위한 에러 화면 구현과 함께, 204 응답 처리 로직을 개선하여 null이나 content가 없는 경우에도 안정적으로 동작하도록 수정했습니다.
- `ErrorScreen` 컴포넌트 구현
- 재사용 가능한 에러 메시지 표시 컴포넌트
- 204 응답 처리 개선
- null 응답 처리 로직 추가
- content가 없는 경우에도 오류 없이 처리
- Closes #147 
- 현재는 로그인 후 레이아웃에만 적용되어있습니다. 추후 전체 에러 바운더리 적용이 필요합니다.
=> Feat/#147 Error 화면 구성 및 204 응답 처리 개선

src/app/(main)/(places)/page.tsx, src/features/community/components/comment-input/CommentInput.tsx, src/features/onboarding/components/kakao-login-button/KakaoLoginButton.tsx, src/features/place/components/category-list/Category.tsx, src/features/place/components/category-list/CategoryList.tsx, src/features/place/components/place-item/PlaceItem.tsx, src/features/place/components/place-menu/ToggleMenuButton.tsx, src/features/place/components/search-bar/SearchBar.tsx, src/features/place/components/search-result-bar/SearchResultBar.tsx, src/features/user/components/delete-account/DeleteAccountForm.tsx, src/shared/components/bottom-navigation/BottomNavigationItem.tsx, src/shared/components/button/Button.tsx, src/shared/components/dropdown-menu/DropdownMenu.tsx, src/shared/components/header/Header.tsx, src/shared/components/select/Select.tsx, src/shared/components/sheet/Sheet.tsx, src/shared/components/tab/Tabs.tsx
사용자 경험 향상을 위한 UI 컴포넌트 스타일 개선을 진행했습니다.
클릭 가능한 요소의 시각적 피드백, 카테고리바의 디자인을 개선하여 더 직관적이고 사용하기 편한 인터페이스를 제공합니다.
- **클릭 가능한 컴포넌트 개선**
- 클릭 가능한 요소에 `cursor-pointer` 추가
- 웹 환경에서 클릭 가능함을 명확히 표시
- **입력창 가독성 개선**
- 입력창의 글씨 크기 조정
- **카테고리바 디자인 개선**
- 카테고리 선택 버튼의 시각적 디자인 개선
- hover 효과 및 애니메이션 추가로 인터랙션 품질 향상
- 더 모던하고 세련된 UI 제공
Closes #169
- 클릭 가능한 요소의 시각적 피드백이 일관되게 적용되었는지 확인 필요
- 카테고리바의 애니메이션이 성능에 영향을 주지 않는지 모니터링 필요
- 입력창 글씨 크기 변경으로 인한 레이아웃 변화가 없는지 확인 필요
=> Style/#169 클릭 가능 요소 및 카테고리바 디자인 개선

src/features/place/constants/map.ts, src/features/place/utils/map.ts, src/shared/lib/map.ts
카카오맵에 클러스터링(클러스트) 라이브러리를 적용하여, 많은 마커가 지도에 표시될 때 가독성과 성능을 개선하였습니다.  
---
- 카카오맵 클러스터링 라이브러리(`clusterer`) 추가 및 적용
- 클러스터 클릭 시 해당 위치로 지도 줌인 기능 구현
- 지도 최대 레벨(map level) 조정
---
- 카카오맵 SDK에 `libraries=services,clusterer` 옵션 추가
- 클러스터 스타일(핑크 계열, 그라데이션, 블러 효과 등) 커스텀
- 클러스터 클릭 시 한 단계 확대(줌인)되는 이벤트 핸들러 추가
- 마커가 많은 경우에도 클러스터가 잘 유지되도록 minLevel, gridSize 등 파라미터 조정
- 지도 최대/최소 레벨 설정
---
Closes #167 
---
---
---
- 클러스터 스타일 및 파라미터는 추후 UX 피드백에 따라 추가 조정될 수 있습니다.
- 클러스터링 적용 후 마커 개수에 따라 성능이 달라질 수 있으니, 대량 데이터 환경에서 추가 테스트 필요
=> Feat/#167 카카오맵 클러스터링 적용

Jenkinsfile, appspec.yml, scripts/AfterInstall.sh, scripts/ApplicationStart.sh, scripts/BeforeInstall.sh, scripts/NotifyDiscord.sh, src/shared/hooks/useImageUpload.ts
GCP 환경에서 운영되던 기존 배포 파이프라인을 AWS 기반으로 전환하고, CodeDeploy를 활용한 배포 자동화 구조로 통합하였습니다.
- CodeDeploy 배포용 스크립트 작성
- BeforeInstall.sh: 기존 컨테이너 종료 및 삭제
- AfterInstall.sh: ECR 인증, 이미지 pull 및 image ref 저장
- ApplicationStart.sh: pulled 이미지 실행
- NotifyDiscord.sh: 배포 성공 시 Discord 알림 전송
- appspec.yml: 배포 후크 구성
- S3 이미지 업로드 presigned PUT 요청 시 x-amz-acl: bucket-owner-full-control 헤더 추가
- GCP → AWS 환경 전환에 따른 Jenkins 파이프라인 전면 리팩토링
=> Deploy: GCP → AWS 전환 및 CodeDeploy 기반 배포 파이프라인 리팩토링

src/app/(main)/moments/page.tsx, src/features/community/components/comment-section/CommentSection.tsx, src/features/community/components/index.ts, src/features/community/components/moments-client/MommentsClient.tsx, src/features/community/components/moments-client/index.ts, src/features/community/components/scroll-top-button/ScrollTopButton.tsx, src/features/community/components/scroll-top-button/index.ts, src/features/community/hooks/index.ts, src/features/community/hooks/useCommentMutations.ts, src/features/community/hooks/useInfiniteScroll.ts, src/features/community/stores/index.ts, src/features/community/stores/momentScrollStore.ts, src/features/place/components/place-list-bottom-sheet/PlaceListBottomSheet.tsx, src/features/place/hooks/index.ts, src/shared/hooks/index.ts, src/shared/hooks/useImageInput.ts, src/shared/hooks/useImageUpload.ts, src/shared/hooks/useScrollRestoration.ts
댓글 기능 개선, 무한 스크롤 및 스크롤 복원, 맨 위로 이동 버튼 등 사용자 경험을 향상시키는 주요 기능을 추가 및 리팩터링하였습니다.  
TanStack Query 기반의 데이터 관리로 성능과 유지보수성을 높였습니다.
---
- 댓글 작성/삭제 기능에 TanStack Query 기반 커스텀 훅(`useAddComment`, `useDeleteComment`) 적용
- MomentsClient 컴포넌트 구현 및 `useScrollRestoration` 훅 적용
- 맨 위로 이동 버튼(ScrollTopButton) 구현
- 댓글 관련 TanStack Query 커스텀 훅 추가
- `useInfiniteScroll` 커스텀 훅을 TanStack Query 기반으로 리팩터링
- `useMomentScrollStore` 전역 상태 추가
- 누락된 `'use client'` 키워드 추가
---
Closes #189
---
---
---
- TanStack Query 기반으로 데이터 관리 방식이 변경되어, 캐시 및 상태 동기화에 유의해야 합니다.
- 기존 커스텀 훅 사용처에서 새로운 API에 맞게 수정되었는지 확인이 필요합니다.
- `'use client'` 누락 시 클라이언트 훅이 정상 동작하지 않을 수 있으니, 관련 파일을 다시 한 번 점검해 주세요.
=> Feat/#189  기록 Tanstack Query으로 마이그레이션

Jenkinsfile
CI 과정에서 CDN 환경 변수를 주입할 수 있도록 Jenkinsfile을 수정하였습니다.
- CDN 환경 변수 추가
=> Deploy: CDN 환경변수 추가

src/features/community/components/moment-form/MomentImagesInput.tsx, src/features/community/components/moment-image-slider/MomentImageSlide.tsx, src/features/place/components/place-basic-info/PlaceBasicInfo.tsx, src/features/place/components/place-item/PlaceItem.tsx, src/features/user/components/profile-form/ProfileImageInput.tsx, src/shared/components/user-avatar/UserAvatar.tsx
프로젝트 전역에서 사용하던 `<img>` 태그를 Next.js의 `<Image />` 컴포넌트로 일괄 변경하였습니다.  
이를 통해 이미지 최적화, 자동 리사이즈, lazy loading 등 Next.js의 이미지 최적화 기능을 전면적으로 활용할 수 있게 되었습니다.
---
- 기존 `<img>` 태그를 Next.js `<Image />` 컴포넌트로 전역적으로 교체
- 각 이미지에 width/height, alt 등 필수 속성 추가
- fill, object-fit 등 다양한 이미지 스타일에 맞게 마이그레이션
---
- closes #171
---
---
- 외부 이미지 도메인 등록이 누락되지 않았는지 점검 필요
- fill 사용 시 부모 요소에 position과 크기 지정이 올바른지 확인 필요
=> Refactor/#171 이미지 전역 Next/Image 컴포넌트 적용

next.config.ts, src/features/community/components/moment-form/MomentImagesInput.tsx, src/features/community/components/moment-image-slider/MomentImageSlide.tsx, src/features/place/components/place-basic-info/PlaceBasicInfo.tsx, src/features/place/components/place-item/PlaceItem.tsx, src/features/user/components/profile-form/ProfileImageInput.tsx, src/shared/components/user-avatar/UserAvatar.tsx
이미지 렌더링을 Next.js `<Image />` 컴포넌트로 일괄 변경하여 성능과 유지보수성을 개선합니다.  
또한, CDN 주소를 환경 변수로 관리하도록 개선하여 배포 환경별 유연성을 높였습니다.
---
| 타입      | 커밋 번호 | 주요 변경 내용                                              |
| --------- | -------- | --------------------------------------------------------- |
| Chore     | #194     | CDN 주소를 환경 변수(env 파일)로 관리하도록 변경              |
| Refactor  | #171     | 프로젝트 전역의 이미지 컴포넌트를 Next/Image로 일괄 변경      |
---
- closes #194
- closes #171
---
---
- CDN 주소가 환경 변수로 관리되므로, 배포 환경별 `.env` 파일을 반드시 확인해야 합니다.
=> Release: v2.3.3 – Image Optimization, and CDN Config 

next.config.ts, package.json, pnpm-lock.yaml, src/app/layout.tsx
=> Release: v2.3.4 – Google Analytics Integration

Jenkinsfile, src/app/sitemap.ts
코드 품질 개선과 SEO 최적화를 위한 사이트맵 API 변경을 통해 서비스의 안정성과 검색 엔진 최적화를 향상시켰습니다. 
불필요한 코드 정리와 함께 사이트맵 구조를 개선하여 검색 엔진 크롤링 효율성을 높였습니다.
---
| 타입      | 커밋 번호 | 주요 변경 내용                                              |
| --------- | -------- | --------------------------------------------------------- |
| Chore     | -        | 불필요한 개행 문자(\n) 삭제로 코드 정리                      |
| Feat      | #217     | 사이트맵 API 구조 변경 및 최적화                              |
---
- closes #217
---
---
- **사이트맵 구조**: 변경된 사이트맵 구조가 모든 페이지를 올바르게 포함하는지 확인 필요
- **검색 엔진 인덱싱**: 새로운 사이트맵 구조로 인한 검색 엔진 재크롤링 시간 고려 필요
- **코드 품질**: 개행 문자 삭제로 인한 코드 가독성 영향 없는지 확인 필요
- **API 호환성**: 사이트맵 API 변경이 다른 시스템과의 연동에 영향을 주지 않는지 검증 필요
- **성능 모니터링**: 사이트맵 생성 및 제공 성능 개선 효과 지속적 모니터링 필요
---
- **코드 정리**: 불필요한 개행 문자 제거로 코드 품질 향상
- **SEO 최적화**: 사이트맵 구조 개선으로 검색 엔진 크롤링 …
=> Release: v2.3.5 – 코드 정리 및 Sitemap API 변경
