100-hours-a-week/7-team-ddb-fe

src/app/(main)/(places)/places/[id]/page.tsx, src/app/globals.css, src/features/place/components/index.ts, src/features/place/components/place-basic-info/PlaceBasicInfo.tsx, src/features/place/components/place-basic-info/index.ts, src/features/place/components/place-menu/PlaceMenu.tsx, src/features/place/components/place-menu/index.ts, src/features/place/components/place-open-hours/PlaceOpenHours.tsx, src/features/place/components/place-open-hours/index.ts, src/features/place/index.ts, src/features/place/types/index.ts, src/features/place/types/place.ts
장소 상세 페이지(`places/[id]`)를 구현했습니다. 장소의 기본 정보, 영업 시간, 메뉴 정보를 보여주는 페이지를 추가했습니다.
- `PlaceBasicInfo`: 장소의 기본 정보(이름, 주소, 전화번호, 키워드, 설명)를 보여주는 컴포넌트
- `PlaceOpeningHours`: 영업 시간 정보를 보여주는 컴포넌트
- `PlaceMenu`: 메뉴와 가격 정보를 보여주는 컴포넌트
- `PlaceDetail`: 장소 상세 정보를 위한 타입 정의
- `Menu`: 메뉴 정보를 위한 타입 정의
- `OpenHours`: 영업 시간 정보를 위한 타입 정의
- 스크롤바 스타일을 글로벌로 설정하여 일관된 UI 제공
- 모바일 환경에 최적화된 레이아웃 구현
Closes #18 
- 현재는 mock 데이터를 사용하고 있으며, 추후 API 연동 예정
- 위치 정보 권한이 필요할 수 있음 (새로고침해야 잘나오는 현상이 있음)
- 이미지 최적화가 필요할 수 있음
=> Feat/#18 장소 세부 조회 페이지 구현

src/app/(main)/(places)/page.tsx, src/app/(main)/(places)/search/layout.tsx, src/app/(main)/(places)/search/page.tsx, src/features/place/api/searchPlaces.ts, src/features/place/components/category-list/Category.tsx, src/features/place/components/map/Map.tsx, src/features/place/components/place-bottom-sheet/PlaceBottomSheet.tsx, src/features/place/components/place-item/PlaceItem.tsx, src/features/place/components/place-list/PlaceList.tsx, src/features/place/components/search-bar/SearchBar.tsx, src/features/place/constants/index.ts, src/features/place/constants/map.ts, src/features/place/types/place.ts, src/features/place/utils/map.ts
이 PR은 장소 바텀 시트에 장소 데이터를 받아서 그려지도록 기능을 추가하고, map 컴포넌트가 장소 데이터를 받아서 핀을 그리도록 수정합니다.
- 장소 바텀 시트에 장소 데이터 받아서 그리도록 추가
- map 컴포넌트가 장소 데이터를 받아서 핀을 그리도록 수정
- 장소 리스트 컴포넌트가 장소 props를 받도록 추가
- map 관련 상수를 내보내기
- place 타입 정의
- 검색 페이지로 이동할 때 위도, 경도 값을 포함하도록 추가
- API 임시 더미 데이터 사용으로 변경
- 맵 페이지 구성
- 맵 관련 상수를 별도의 폴더에서 관리하도록 변경
=> Feat/#40 장소 API 연동

src/features/user/components/profile-form/ProfileForm.tsx, src/shared/api/getPresignedUrl.ts, src/shared/api/index.ts, src/shared/hooks/index.ts, src/shared/hooks/useImageUpload.ts
이번 PR은 이미지 업로드 기능을 개선하고 프로필 폼에 적용하는 것을 주요 내용으로 합니다. 이미지 업로드를 위한 커스텀 훅과 API 함수를 정의하였으며, 이를 프로필 폼에서 사용하여 사용자가 프로필 이미지를 업로드할 수 있도록 기능을 구현했습니다.
- 이미지 업로드 관련 로직을 캡슐화하고 재사용성을 높이기 위해 커스텀 React Hook (`useImageUpload`)을 정의했습니다.
- 이미지 Presigned URL을 요청하고 GCS에 업로드하는 과정을 처리합니다.
- 이미지 업로드를 위한 백엔드 API 통신 함수 (`getPresignedUrl`)를 정의했습니다.
- `ProfileForm` 컴포넌트에서 `useImageUpload` 훅과 API 함수를 사용하여 이미지 업로드 기능을 구현했습니다.
- 사용자가 이미지를 선택하면 미리보기를 제공합니다.
- 폼 제출 시 선택된 이미지를 GCS에 업로드하고, 반환된 이미지 URL을 프로필 정보와 함께 저장합니다.
- 업로드 중 로딩 상태 및 오류 발생 시 적절한 UI 피드백을 제공합니다.
Closes #44
=> Feat/#44 프로필 이미지 업로드 API 연동

src/app/(main)/(places)/places/[id]/page.tsx, src/features/place/api/getPlaceDetail.ts, src/features/place/components/place-open-hours/PlaceOpenHours.tsx, src/features/place/types/place.ts, src/shared/components/header/Header.tsx
이번 PR은 장소 상세보기 페이지의 기능 개선 및 코드 정리를 주요 내용으로 합니다. 상세보기 페이지에 API를 연동하여 실제 데이터를 표시하도록 구현했으며, 영업시간 정보가 없는 경우 '휴무'로 표시되도록 UI를 개선했습니다. 또한, 중복된 타입 정의를 정리하고 헤더 컴포넌트의 뒤로 가기 동작을 유연하게 변경했습니다.
- **장소 상세보기 페이지 API 연동**:
- 장소 상세 정보를 불러오는 API를 호출하여 페이지에 실제 데이터를 연동했습니다.
- 이를 통해 사용자는 특정 장소에 대한 상세한 정보를 확인할 수 있습니다.
- **영업시간 표시 개선**:
- 장소의 영업시간(`hours`) 정보가 없는 (`null`) 경우, '휴무'로 표시되도록 UI 로직을 변경했습니다. (기존 `note` 관련 로직 제거)
- **중복 타입 정리**:
- 프로젝트 내에 중복으로 정의되어 있던 타입들을 식별하고 정리하여 코드의 일관성과 유지보수성을 향상했습니다.
- **헤더 뒤로 가기 기능 유연화**:
- 헤더 컴포넌트에서 `onBackClick` 함수가 별도로 정의되지 않은 경우, 기본적으로 `router.back()`을 호출하여 이전 페이지로 이동하도록 설정했습니다.
Closes #46 
- 장소 상세 API의 응답 형식 및 데이터 유효성에 대한 최종 확인이 필요합니다.
- 다양한 장소 데이터(영업시간 유/무, 모든 필드 데이터 유/무 등)에 대해 상세보기 페이지가 올바르게 렌더링되는지 충분한 테스트가 필요합니다.
=> Feat/#46 장소 상세 페이지 API 연동

src/app/(main)/(places)/places/[id]/page.tsx, src/features/place/components/place-menu/PlaceMenu.tsx, src/features/place/components/place-menu/ToggleMenuButton.tsx, src/features/place/components/place-open-hours/PlaceOpenHours.tsx, src/features/place/types/place.ts, src/features/user/components/profile/Profile.tsx
이 PR은 장소 상세페이지의 UI를 보완하여 사용자 경험을 개선합니다. 메뉴가 5개 이상일 경우 '메뉴 더보기' 버튼을 추가하여 나머지 메뉴를 펼쳐볼 수 있도록 하였으며, 영업 시간에 브레이크 타임을 명시하여 정보를 더욱 명확하게 전달합니다.
- 메뉴가 5개 이상일 경우 '메뉴 더보기' 버튼을 추가하여 나머지 메뉴를 펼쳐볼 수 있도록 기능 추가
- 영업 시간에 브레이크 타임 정보를 추가하여 사용자에게 명확한 정보를 제공
- 메뉴 및 영업 시간 정보가 없을 경우 해당 섹션이 보이지 않도록 스타일 수정
- 이미지 정렬 문제 수정
Closes #48 
- UI 변경사항이 사용자 경험에 미치는 영향을 고려하여 리뷰 부탁드립니다.
=> Feat/#48 장소 상세페이지 보완 (휴게시간, 메뉴 UI)

src/app/(main)/(places)/search/layout.tsx, src/app/(main)/(places)/search/page.tsx, src/app/(main)/mypage/page.tsx, src/app/globals.css, src/app/layout.tsx, src/features/place/components/place-basic-info/PlaceBasicInfo.tsx, src/features/place/components/place-item/PlaceItem.tsx, src/features/place/components/place-list/PlaceList.tsx
이 PR은 장소 검색 기능과 관련된 UI/UX를 개선했습니다.
주요 변경 사항으로는 장소 리스트의 높이 표시 방식을 일관성 있게 조정하고, 검색 중 로딩 화면 및 검색 결과가 없을 때의 화면을 명확하게 구성하여 사용자 경험을 향상시키는 데 중점을 두었습니다.
- **장소 리스트(PlaceList) 높이 표시 방식 개선**
- `PlaceList` Drawer의 초기 높이가 일관되지 않게 표시되던 문제를 수정하여, 콘텐츠 유무 및 상태에 따라 예측 가능한 높이로 표시되도록 조정했습니다.
- 스타일을 수정하여 장소 리스트의 전체적인 높이 설정을 명확히 했습니다.
- **검색 경험 개선**
- 장소 검색 시 사용자에게 로딩 중임을 알리는 화면을 추가했습니다.
- 검색 결과 데이터가 없을 경우, "검색된 장소가 없습니다"라는 메시지를 명확히 표시하도록 `PlaceList` 컴포넌트를 수정했습니다.
- 로딩 화면의 레이아웃을 일관성 있게 설정했습니다.
- **이미지 처리 보완**
- 장소 이미지 데이터가 없을 경우, 기본 더미 이미지가 표시되도록 수정하여 UI 깨짐을 방지했습니다.
Closes #57 
- `PlaceList`의 높이 관련 변경 사항이 다양한 디바이스 및 화면 크기에서 의도대로 동작하는지 충분한 테스트가 필요합니다.
=> Feat/#57 로딩 화면 및 예외 화면 생성

src/app/(auth)/auth/consent/page.tsx, src/app/(auth)/oauth/kakao/callback/KakaoCallbackClient.tsx, src/features/user/api/issueAuthTokens.ts, src/features/user/api/postAgreement.ts, src/features/user/types/token.ts
이 PR은 백엔드와의 타입 통일 및 상세 페이지에서 일부 정보가 없을 때도 정상적으로 동작하도록 UI/UX를 개선합니다.
- 백엔드와 프론트엔드 타입 정의를 통일하여 데이터 일관성을 확보 (`refactor: 백엔드와 타입 통일`)
- 상세 페이지에서 주소, 전화번호 정보가 없어도 정상적으로 렌더링되도록 수정 (`fix: 상세 페이지 주소, 폰 번호 정보 없어도 정상적으로 나오도록 수정`)
- 상세 페이지 메뉴에서 가격 정보가 없어도 정상적으로 표시되도록 예외 처리 (`fix: 상세 페이지 메뉴 가격 없어도 정상적으로 나오도록 수정`)
Closes #39 
- 타입 변경에 따라 기존 데이터와의 호환성에 유의해 주세요.
=> Refactor/#39 백엔드와 변수명 개선

src/app/(main)/(places)/search/page.tsx, src/app/layout.tsx, src/shared/providers/QueryProvider.tsx, src/shared/providers/index.ts
장소 상세보기 페이지에서 뒤로가기 버튼 클릭 시, search 페이지에서 불필요하게 재검색이 발생하는 문제를 개선합니다.  
동일한 쿼리 키에 대해 10분 동안 fresh 상태를 유지하여, 사용자가 검색 결과를 다시 볼 때 빠르고 쾌적한 UX를 제공합니다.
- tanstack query의 `staleTime`을 10분(600,000ms)으로 설정
- `refetchOnWindowFocus`, `refetchOnMount` 옵션을 false로 설정하여 불필요한 refetch 방지
- 뒤로가기 시 캐시된 데이터가 즉시 노출되도록 개선
Closes #61 
- 10분 이후에는 데이터가 stale 처리되어 재검색이 발생할 수 있습니다.
- 쿼리 파라미터가 변경되면 새로운 검색이 정상적으로 동작하는지 확인 필요
=> Refactor/#61 장소 상세보기 → 뒤로가기 시 search 재검색 개선

src/app/(auth)/oauth/kakao/callback/page.tsx, src/app/(main)/moments/page.tsx, src/app/globals.css, src/features/place/components/map/Map.tsx, src/features/place/components/place-list/PlaceList.tsx
모바일 환경에서 주소창, 툴바 등 브라우저 UI에 의해 뷰포트 높이가 변동되는 문제를 해결하기 위해  
가장 작은 뷰포트 높이(svh)를 기준으로 레이아웃이 계산되도록 수정하였습니다.
- CSS height 단위를 기존 `vh`에서 `svh`로 변경
- 모바일 브라우저에서 주소창, 툴바 등 UI가 보이거나 숨겨질 때도 레이아웃이 안정적으로 유지됨
- 주요 레이아웃 컴포넌트의 높이 단위를 `svh`로 적용
- 모바일 환경에서 레이아웃 점프 및 흔들림 현상 개선
- 일부 구형 브라우저에서는 `svh` 단위가 지원되지 않을 수 있으니, 브라우저 호환성 확인 필요
=> Style/#76 가장 작은 뷰포트 높이 기준으로 계산하도록 수정 (모바일 주소창, 툴바 고려)

src/app/layout.tsx, src/shared/components/feedback-button/FeedbackButton.tsx, src/shared/components/feedback-button/index.ts, src/shared/components/index.ts
마이페이지 하단에 고정된 피드백 버튼 컴포넌트를 추가하였습니다.  
사용자는 버튼을 클릭하여 구글 폼을 통해 피드백을 남길 수 있습니다.
- 오른쪽 하단에 고정된 동그란 피드백 버튼 컴포넌트 추가
- 연핑크 단색 배경, 하트편지(💌) 이모지, "피드백 남기러 가기" 텍스트 적용
- 모바일 환경에서는 버튼이 보이지 않도록 처리
- 버튼 클릭 시 새 탭에서 구글 폼으로 이동
- `FeedbackButton` 컴포넌트 생성 및 스타일링
- 접근성(aria-label) 및 반응형 대응
- Closes #73 
- 버튼 색상 및 위치는 디자인 가이드에 따라 추후 변경될 수 있음
- 구글 폼 URL이 변경될 경우 컴포넌트 내 URL도 함께 수정 필요
=> Feat/#73 피드백 버튼 구현

src/app/(auth)/auth/consent/page.tsx, src/features/user/components/consent/ConsentCard.tsx, src/features/user/components/consent/LocationConsent.tsx, src/features/user/components/consent/PrivacyConsent.tsx, src/features/user/components/consent/index.ts, src/features/user/components/index.ts, src/features/user/hooks/index.ts, src/features/user/hooks/useConsent.ts
Consent 페이지의 컴포넌트 구조를 개선하여 코드의 재사용성과 유지보수성을 향상시켰습니다. 커스텀 훅을 도입하여 상태 관리 로직을 분리하고, 공통 컴포넌트를 만들어 UI 일관성을 유지했습니다.
- Consent 페이지 컴포넌트 분리
- `ConsentCard`: 공통 카드 UI 컴포넌트
- `PrivacyConsent`: 개인정보 수집 동의 컴포넌트
- `LocationConsent`: 위치기반 서비스 동의 컴포넌트
- 커스텀 훅 도입
- `useConsent`: 동의 상태 관리 및 API 호출 로직 분리
- 체크박스 상태 관리
- 동의 API 호출 및 라우팅 처리
- Closes #67 
- 기존 기능과 동일하게 동작하는지 확인이 필요합니다.
- 스타일링이 기존과 동일하게 유지되었는지 확인해주세요.
- 체크박스 상태 변경 시 모든 동의 체크박스가 정상적으로 동작하는지 확인해주세요.
=> Refactor/#67 정보 동의 페이지 컴포넌트 및 custom hook 으로 상태 관리

.gitignore, package.json, src/features/user/api/getOAuthRedirectUrl.ts, src/features/user/api/issueAuthTokens.ts, src/features/user/utils/getRedirectUri.ts, src/features/user/utils/index.ts
로컬 개발 환경에서 백엔드 dev 서버와의 연동을 위한 설정을 추가합니다. 이를 통해 로컬에서 개발 시 백엔드 dev 서버의 API를 사용할 수 있도록 합니다.
- OAuth 리다이렉트 URI 설정
- 로컬 환경에서 `NEXT_PUBLIC_OAUTH_REDIRECT_URI` 환경 변수 사용
- HTTPS 및 도메인 설정
- `test.dev.dolpin.site`로 호스팅되도록 설정
- HTTPS 프로토콜 사용 설정
- 보안 설정
- certificates 파일을 gitignore에 추가
- 민감한 인증 정보 보호
- Closes #103 
- API 요청이 정상적으로 전달되는지 확인
- 응답이 정상적으로 수신되는지 확인
- 로컬 환경에서 카카오 로그인 정상 작동 확인
- 리다이렉트 URI가 정상적으로 처리되는지 확인
- `test.dev.dolpin.site` 도메인으로 정상 접속 확인
- HTTPS 프로토콜 정상 작동 확인
1. **환경 변수 설정**
- 로컬 개발 시 `.env` 파일에 `NEXT_PUBLIC_OAUTH_REDIRECT_URI` 설정 필요
- 환경 변수가 없을 경우 백엔드에서 설정 된 기본값 사용
2. **보안**
- certificates 파일은 git에 커밋하지 않기
- 민감한 인증 정보는 환경 변수로 관리
3. **백엔드 연동**
- 백엔드 dev 서버가 정상적으로 동작 중인지 확인
- CORS 설정이 올바른지 확인
```env
NEXT_PUBLIC_OAUTH_REDIRECT_URI=http://localhost:3000/oauth/kakao/callback
```
=> Feat/#103 로컬 환경에서 백엔드 dev 바라보도록 설정

Jenkinsfile
prod와 dev 환경의 배포가 금요일에 동시에 실행될 경우 Jenkins 서버의 CPU 사용량이 급증하여 성능 저하가 발생하는 문제가 있었습니다. 이를 방지하기 위해 cron 설정을 조정하여 금요일에 두 배포 작업이 겹치지 않도록 시간대를 분리하였습니다.
- Jenkins 파이프라인의 cron 트리거 중 금요일 dev 배포 시간 변경
- 기존: 금요일 오전 9시 30분
- 변경: 금요일 오전 10시 0분
- Jenkins CPU 부하 완화 목적의 시간 분산 적용
=> deploy: cron 시각 변경

src/features/user/components/profile-form/ProfileForm.tsx, src/features/user/components/profile-form/ProfileImageInput.tsx, src/features/user/schemas/index.ts, src/features/user/schemas/profile.ts, src/shared/hooks/index.ts, src/shared/hooks/useImageInput.ts, src/shared/hooks/useImageUpload.ts
프로필 이미지 업로드 관련 코드를 모듈화하여 재사용성과 유지보수성을 개선했습니다. Zod 스키마, 이미지 업로드 로직, UI 컴포넌트를 각각 분리하여 관심사를 명확히 분리했습니다.
- **Zod 스키마 분리**
- 프로필 폼의 유효성 검사 로직을 별도의 스키마 파일로 분리
- 재사용 가능한 타입 정의 추가
- **이미지 업로드 로직 분리**
- `useImageInput` 커스텀 훅 생성
- 이미지 파일 처리, 미리보기, 업로드 상태 관리 로직 캡슐화
- 단일/다중 이미지 업로드 지원
- **UI 컴포넌트 분리**
- `ProfileImageInput` 컴포넌트 생성
- 이미지 업로드 UI 로직을 재사용 가능한 컴포넌트로 분리
- 프로필 폼의 복잡도 감소
Closes #134 
- 이미지 업로드 시 메모리 누수 방지를 위해 `URL.createObjectURL` 생성된 URL을 컴포넌트 언마운트 시 정리하도록 구현했습니다.
- 다중 이미지 업로드 기능은 현재 프로필 이미지에서는 사용하지 않지만, 향후 확장성을 고려하여 `useImageInput` 훅에 구현되어 있습니다.
=> Refactor/#134 ProfileForm 로직, 컴포넌트 분리

package.json, pnpm-lock.yaml, src/app/(main)/layout.tsx, src/app/(main)/moments/page.tsx, src/app/(main)/mypage/page.tsx, src/features/community/components/author-info/AuthorInfo.tsx, src/features/community/components/moment-list/MomentItem.tsx, src/features/community/components/moment-list/MomentList.tsx, src/features/place/components/index.ts, src/features/place/components/place-item/PlaceItem.tsx, src/features/place/components/place-list-bottom-sheet/PlaceListBottomSheet.tsx, src/features/place/components/place-list/PlaceList.tsx, src/features/place/components/place-list/index.ts, src/features/place/types/place.ts, src/features/user/components/index.ts, src/features/user/components/profile-settings-sheet/ProfileSettingsSheet.tsx, src/features/user/components/profile-settings-sheet/index.ts, src/features/user/components/profile-tabs/ProfileTabs.tsx, src/features/user/components/profile-tabs/index.ts, src/shared/components/full-screen-message/FullScreenMessage.tsx, src/shared/components/index.ts, src/shared/components/sheet/Sheet.tsx, src/shared/components/sheet/index.ts, src/shared/components/tab/Tabs.tsx, src/shared/components/tab/index.ts
사용자가 자신의 활동 내역을 확인할 수 있는 마이페이지를 구현하였습니다. 이를 위해 설정 메뉴(`Sheet`), 탭(`Tabs`) 등 신규 컴포넌트를 추가하고, 기존 장소 리스트 컴포넌트를 재사용 가능하도록 리팩토링하는 작업을 진행했습니다.
- **마이페이지 UI 구현 및 기능 적용**
- `UserMenuSheet` (설정, 로그아웃 등) 및 `ProfileTabs` (내 기록, 북마크) 컴포넌트 적용
- 더미데이터를 사용하여 마이페이지 화면 구성
- **컴포넌트 리팩토링 및 재사용성 강화**
- `PlaceList` 컴포넌트를 `PlaceListBottomSheet`에서 분리하여 마이페이지에서도 재사용
- `FullScreenMessage` 컴포넌트가 `className`을 props로 받도록 개선하여 스타일 유연성 확보
- **페이지 이동 및 인터랙션 추가**
- 프로필 이미지/이름 클릭 시 해당 유저 프로필 페이지로 이동
- 기록 아이템 클릭 시 기록 상세 페이지로 이동
- **레이아웃 및 스타일 개선**
- 메인 레이아웃 및 `moment` 페이지의 높이(`h-full`) 관련 스타일 수정
- **`UserMenuSheet.tsx`**: `shadcn/ui`의 `Sheet`를 기반으로 '회원 정보 수정', '탈퇴', '로그아웃' 메뉴를 제공하는 컴포넌트를 구현하고 마이페이지에 적용했습니다.
- **`ProfileTabs.tsx`**: `shadcn/ui`의 `Tabs`를 기반으로 '내 기록'과 '북마크'를 전환해서 볼 수 있는 탭 컴포넌트를 구현했습니다.
- **`PlaceList.tsx` …
=> Feat/#139  마이페이지 북마크 장소 리스트 & 기록 리스트 UI 구현 

src/app/(main)/mypage/page.tsx, src/features/user/api/getUser.ts
북마크한 장소와 기록 리스트를 서버 API와 연동하고, 서버 사이드에서의 유저 인증 처리를 개선했습니다.
- 북마크 장소 리스트 API 연동
- 북마크한 장소 목록 조회
- 기록 리스트 API 연동
- 사용자 기록 목록 조회
- `getUser` API 쿠키 기반 인증 구현
- 서버 사이드 API 호출 시 쿠키 값 활용
- Closes #140 
- 북마크 목록 조회
- 북마크 상태 변경
- 기록 목록 조회
- 서버 사이드 API 호출 시 쿠키 값이 필요합니다
=> Feat/#140 장소 북마크 장소 리스트 & 기록 리스트 API 연결

src/features/community/components/moment-detail-owner-dropdown/MomentDetailOwnerDropdown.tsx, src/features/community/components/write-moment-fab/WriteMomentFab.tsx, src/features/user/components/profile-settings-sheet/ProfileSettingsSheet.tsx
작성, 수정, 탈퇴 페이지와 같이 히스토리에 남길 필요가 없는 페이지들의 네비게이션을 개선하여 사용자 경험을 향상시켰습니다.
- 작성 페이지 (`/moments/new'`) 히스토리 제거
- 수정 페이지 (`/moments/${momentId}/edit`, `/mypage/delete`) 히스토리 제거
- 탈퇴 페이지 (`/mypage/delete`) 히스토리 제거
- `Link` 컴포넌트에 `replace` prop 추가
- 프로그래매틱 네비게이션에 `router.replace()` 적용
Closes #157 
- 히스토리가 제거되므로 사용자가 브라우저의 뒤로가기 버튼으로 해당 페이지로 돌아갈 수 없음
- 페이지 새로고침 시에는 히스토리가 남을 수 있음 (브라우저 기본 동작)
=> Feat#157 작성,수정,탈퇴 페이지에 히스토리 안남도록 설정

src/app/(main)/(places)/places/[id]/page.tsx, src/features/community/api/getMoments.ts, src/features/community/components/index.ts, src/features/community/components/moment-list/MomentList.tsx, src/features/community/components/place-moment-section/PlaceMomentSection.tsx, src/features/community/components/place-moment-section/index.ts, src/features/community/types/moment.ts
장소 상세보기 페이지에 장소별 기록(Moment) 목록을 보여주는 기능을 추가했습니다. 사용자가 특정 장소에서 작성한 기록들을 모아볼 수 있으며, 새로운 기록을 작성할 수 있는 FAB(Floating Action Button)도 추가했습니다.
- `PlaceMomentSection` 컴포넌트 구현
- 장소별 기록 목록을 보여주는 섹션 컴포넌트 추가
- 장소 ID를 기반으로 해당 장소의 기록들을 조회하여 표시
- `MomentList` 컴포넌트 수정
- `placeId` props를 받아 장소별 필터링 기능 추가
- 기록 목록 API 수정
- 장소 타입을 받아 처리할 수 있도록 API 로직 개선
- `WriteMomentFab` 컴포넌트 추가
- 장소 상세 페이지에서 새로운 기록을 작성할 수 있는 FAB 추가
Closes #156 
- 장소별 기록 목록 조회 시 페이지네이션 처리가 필요할 수 있습니다
- 기록 작성 시 장소 정보가 자동으로 연동되어야 합니다
- API 응답 시간에 따른 로딩 상태 처리가 필요합니다
=> Feat/#156 장소에 기록 작성 버튼 및 기록 리스트 추가

package.json, pnpm-lock.yaml, src/features/place/components/category-list/Category.tsx, src/features/place/components/place-list-bottom-sheet/PlaceListBottomSheet.tsx, src/features/place/components/place-sort-select/PlaceSortSelect.tsx, src/features/place/components/place-sort-select/index.ts, src/features/place/components/search-bar/SearchBar.tsx, src/features/place/components/search-result-bar/SearchResultBar.tsx, src/features/place/constants/bottomSheet.ts, src/features/place/constants/index.ts, src/features/place/constants/sortOptions.ts, src/features/place/hooks/index.ts, src/features/place/hooks/useSortedPlaceList.ts, src/features/place/stores/bottomSheetStore.ts, src/features/place/types/bottomSheetStore.ts, src/features/place/types/place.ts, src/shared/components/index.ts, src/shared/components/select/Select.tsx, src/shared/components/select/index.ts
사용자가 장소 리스트를 다양한 기준으로 정렬하여 볼 수 있도록 정렬 기능을 추가하였습니다.  
이를 위해 커스텀 훅, UI 컴포넌트, 전역 상태 관리 로직이 구현되었습니다.
- **정렬 기능 핵심 로직 구현:**
- 장소 리스트 정렬 관련 로직을 `useSortedPlaceList`  커스텀 훅으로 분리
- 검색 타입에 따라 정렬 관련 전역 상태 값 설정 로직 추가
- **UI 컴포넌트 추가:**
- 정렬 옵션을 선택할 수 있는 `PlaceSortSelect` 컴포넌트 신규 추가
- `shadcn/ui`의 `select` 컴포넌트를 기반으로 UI 구성
- **상태 관리 및 타입 정의:**
- 정렬 기능에 필요한 전역 상태 변수 추가 (Zustand 활용)
- 백엔드 장소 데이터 타입과 일치하도록 기존 타입 수정 및 정렬을 위한 `유사도` 등의 타입 추가
- `PlaceSortSelect` 컴포넌트를 통해 사용자가 정렬 기준(예: 거리순, 인기순, 유사도순 등)을 선택 가능
- 카테고리 검색은 '유사도' 선택이 존재하고 존재하지 않음
- 선택된 정렬 기준에 따라 장소 리스트가 실시간으로 재정렬되어 표시
- 정렬 상태는 전역으로 관리되어 다른 컴포넌트나 페이지 이동 시에도 유지될 수 있는 기반 마련
- 데이터 타입 업데이트로 백엔드 스키마 변경과 동기화, 새로운 정렬 기준(유사도) 추가
Closes #89 
- 새로운 정렬 기준 추가 시, 커스텀 훅 및 전역 상태 로직, 타입 정의 부분을 함께 수정해야 합니다.
- `shadcn/ui` select 컴포넌트의 스타일 커스터마이징이 필요할 수 있습니다.
=> Feat/#89 장소 리스트 정렬 기능 추가

src/features/community/api/getComments.ts, src/features/community/api/postComment.ts, src/features/community/components/comment-input/CommentInput.tsx, src/features/community/components/comment-list/CommentItem.tsx, src/features/community/components/comment-list/CommentList.tsx, src/features/community/components/comment-section/CommentSection.tsx, src/features/community/components/moment-detail-client/MomentDetailClient.tsx, src/features/community/stores/commentStore.ts, src/features/community/stores/index.ts, src/features/community/types/comments.ts
댓글 시스템에 대댓글 기능을 추가하여 사용자가 댓글에 답글을 달 수 있도록 구현했습니다.  
---
- 댓글 get, post API에 parent_comment_id 속성 추가
- CommentItemType에 parent_comment_id 속성 추가
- 댓글 시스템에 대댓글 상태 관리 추가
- 댓글 입력창에 답글 모드 UI 추가
- 뒤로가기 시 답글 모드 초기화
- 대댓글 작성 시 실시간 UI 업데이트 및 API 연동
- 대댓글 UI 추가 (계층 구조 표시)
---
Closes #175 
---
---
---
- 대댓글은 현재 1단계까지만 지원합니다 (대댓글의 대댓글은 미지원)
- 대댓글 작성 시 부모 댓글 작성자에게 답글을 남기는 형태입니다
- 페이지 이동 시 답글 모드가 자동으로 초기화됩니다
=> Feat/#175 댓글 시스템 대댓글 기능 추가

appspec.yml, scripts/NotifyDiscord.sh
런타임 환경에서 애플리케이션 컨테이너가 정상 기동되지 않거나, 기동 직후 오류로 인해 반복적으로 재시작되는 경우에도 CodeDeploy는 이를 인식하지 못하고 배포를 성공으로 처리하는 문제가 있었습니다.
이를 해결하기 위해 ValidateService 단계에서 실제 서비스의 커스텀 헬스체크를 수행하도록 추가하였습니다.
- ValidateService 단계에 /api/health에 대한 헬스 체크 스크립트 추가
- 헬스체크 실패 시 Discord 알림 발송 및 CodeDeploy 배포 실패 처리
- 헬스체크 성공 시 정상적으로 배포 완료 알림 발송
=> Deploy: ValidateService 단계에서 health check 진행하여 배포 성공 여부 판단

src/features/place/utils/map.ts
카카오맵 클러스터링에서 클러스터에 포함된 마커(숫자)가 많을수록 색상이 더 진하게 보이도록 스타일을 개선했습니다.  
이를 통해 지도에서 데이터 밀집도를 더 직관적으로 파악할 수 있습니다.
- 클러스터 스타일 배열의 색상 및 투명도 조정
- 숫자가 많을수록(큰 클러스터일수록) 더 진한 색상 적용
Closes #186
=> Style/#186 카카오맵 클러스터 숫자가 많을수록 색상 진해지도록 수정

src/features/place/utils/map.ts
v2.3.1 패치는 카카오맵 클러스터링의 시각적 가독성을 개선하기 위한 스타일 업데이트를 포함합니다.  
클러스터에 포함된 마커(숫자)가 많을수록 색상이 더 진하게 표시되어, 지도에서 데이터 밀집도를 더욱 직관적으로 파악할 수 있습니다.
---
| 타입   | 커밋 번호 | 주요 변경 내용                                         |
| ------ | -------- | ---------------------------------------------------- |
| Style  | #186     | 카카오맵 클러스터 숫자가 많을수록 색상 진해지도록 수정 |
---
- closes #186
- closes #187
---
---
- 클러스터 스타일 변경이 지도 전체 UX에 영향을 줄 수 있으니, 실제 서비스 환경에서 색상 가독성을 꼭 확인해주세요.
- 색상 팔레트는 디자인 가이드에 맞게 추가 조정될 수 있습니다.
=> Release: v2.3.1 – KakaoMap cluster color intensity by marker count #187

src/app/(auth)/oauth/kakao/callback/KakaoCallbackClient.tsx, src/app/(auth)/onboarding/page.tsx, src/app/(main)/login-required/page.tsx, src/features/community/components/comment-input/CommentInput.tsx, src/features/place/hooks/useBookmark.ts, src/features/user/components/profile-settings-sheet/ProfileSettingsSheet.tsx, src/middleware.ts, src/shared/components/global-confirm-dialog/GlobalConfirmDialog.tsx, src/shared/hooks/index.ts, src/shared/hooks/useLoginRequiredAction.ts, src/shared/store/index.ts, src/shared/store/userStore.ts
사용자 인증 기록, 장소 도메인에서 로그인이 가능하도록 개선했습니다.
- **미들웨어 구현**: 로그인이 필요한 페이지 접속 시 자동으로 로그인 요구 페이지로 리다이렉트
- **로그인 요구 페이지**: 사용자 친화적인 로그인 안내 페이지 구현
- **인증 필요 기능 개선**: 
- 댓글 작성 버튼 클릭 시 로그인 안내창 표시
- 북마크 버튼 클릭 시 로그인 안내창 표시
- **로그인 상태 관리**: 로그인/로그아웃 시 전역 상태 자동 업데이트
- **온보딩 페이지 개선**: 로그인 없이 시작하기 버튼 추가로 사용자 진입 장벽 완화
- **UI 컴포넌트 개선**: GlobalConfirmDialog의 글씨 색상을 선택적으로 변경 가능하도록 개선
- **커스텀 훅 구현**: `useLoginRequiredAction` 훅으로 인증 필요 액션 로직 재사용 가능
- **전역 상태 관리**: `useUserStore` 추가로 사용자 상태 전역 관리
Closes #211 
- 로그인 요구 페이지 UI
- 댓글/북마크 버튼 클릭 시 로그인 안내창
- 온보딩 페이지 로그인 없이 시작하기 버튼
- GlobalConfirmDialog 스타일 변경 결과
- 미들웨어 설정이 모든 보호된 라우트에 올바르게 적용되었는지 확인이 필요합니다
- 로그인 상태 변경 시 다른 컴포넌트들의 상태 동기화가 정상적으로 이루어지는지 검증이 필요합니다
- 로그인 없이 시작하기 기능이 기존 로그인 플로우와 충돌하지 않는지 확인이 필요합니다
- 전역 상태 관리 변경으로 인한 성능 영향이 없는지 모니터링이 필요합니다
=> Feat/#211 로그인 없이도 기록, 장소 검색 이용 할 수 있도록 개선
